name: Deploy to VM

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          repository: puffds/dices
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to VM
        run: |
          ssh -o StrictHostKeyChecking=no apavlov@176.109.110.128 << 'EOF'
            cd /home/apavlov/dices/dices
            git pull origin master

            if [ -f "gradlew" ]; then
              chmod +x gradlew
              gradlew build
            else
              echo "gradlew not found!"
              exit 1
            fi
          
            pkill -f 'java -jar' || true
            nohup java -jar build/libs/dices-1.0.jar &
          EOF